@startuml
!include _estilo.iuml
title Casos de uso — Visitante y Estudiante
left to right direction
actor "Visitante" as V
actor "Estudiante" as E
actor "BD Central\nUNIMET" as BD <<sistema>>
actor "PayPal" as PP <<sistema>>
E -|> V
rectangle "Samán Deportivo" {
  usecase "CU-01 Registrarse" as CU01
  usecase "CU-02 Iniciar sesión" as CU02
  usecase "CU-03 Gestionar perfil" as CU03
  usecase "CU-04 Consultar catálogo\nde deportes" as CU04
  usecase "CU-05 Filtrar y buscar\n(deporte, especialidad,\nhorario, cupos)" as CU05
  usecase "CU-06 Ver detalle de deporte\n(cupos en tiempo real,\nhorario, reseñas)" as CU06
  usecase "CU-07 Inscribirse\nen un deporte" as CU07
  usecase "CU-08 Validar solvencia\ny estado" as CU08
  usecase "CU-09 Pagar reserva\nde cupo" as CU09
  usecase "CU-10 Cancelar inscripción" as CU10
  usecase "CU-11 Consultar mis\ninscripciones" as CU11
  usecase "CU-12 Publicar reseña" as CU12
}
V --> CU04
V --> CU06
E --> CU01
E --> CU02
E --> CU03
E --> CU07
E --> CU10
E --> CU11
E --> CU12
CU05 .> CU04 : <<extend>>
CU07 ..> CU08 : <<include>>
CU07 ..> CU09 : <<include>>
CU08 --> BD
CU09 --> PP
@enduml
